spring:
    datasource:
        #driver-class-name: com.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/inventory_management
        username: postgres
        password: KojiSS
    output:
        ansi:
            enabled: ALWAYS
    jpa:

        generate-ddl: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        #database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
    port: 8080
